ENCODING_REPLACEMENT_DICT = {
    'c¿ur': 'coeur',
    '¿uvr': 'oeuvr',
    '¿uf': 'oeuf',
    'n¿ud': 'noeud',
    '¿illets': 'oeillets',
    'v¿ux': 'voeux',
    's¿ur': 'soeur',
    '¿il': 'oeil',
    'protecdtion': 'protection',
    '¿ºtre': 'être',
    'à¢me': 'âme',
    'm¿ºme': 'même',
    'grà¢ce': 'grâçe',
    'con¿u': 'conçu',
    'don¿t': "don't",
    'lorsqu¿': "lorsqu'",
    'jusqu¿': "jusqu'",
    'durabilit¿avec': 'durabilité avec',
    'dâ¿hygiène': "d'hygiène",
    'à¿me': 'âme',
    'durabilit¿': 'durabilité',
    'm¿urs': 'moeurs',
    'd¿coration': 'décoration',
    'tiss¿e': 'tissée',
    '¿cran': 'écran',
    '¿Lastique': 'élastique',
    '¿Lectronique': 'électronique',
    'Capacit¿': 'capacité',
    'li¿ge': 'liège',
    'Kã?Â¿Rcher': 'karcher',
    'Ber¿Ante': 'berçante',
    'durabilitéavec': 'durabilité avec',
    'cahiercaract¿re': 'cahier caractère',
    'Cahierembl¿Me': 'Cahier emblème',
    'c?ur': 'coeur',
    '?uvr': 'oeuvr',
    '?uf': 'oeuf',
    'n?ud': 'noeud',
    '?illets': 'oeillets',
    'v?ux': 'voeux',
    's?ur': 'soeur',
    '?il': 'oeil',
    'man?uvre': 'manoeuvre',
    '?ºtre': 'être',
    'm?ºme': 'même',
    'con?u': 'conçu',
    'don?t': "don't",
    'dâ?hygiène': "d'hygiène",
    'à?me': 'âme',
    'm?urs': 'moeurs',
    'd?coration': 'décoration',
    'tiss?e': 'tissée',
    '?cran': 'écran',
    '?Last': 'élast',
    '?Lectronique': 'électronique',
    'Capacit?': 'capacité',
    'li?ge': 'liège',
    'Ber?Ante': 'berçante',
    'Lâ¿¿Incroyable': "l'incroyable",
    'Creì¿Ateur': 'créateur',
    'cahiercaract?re': 'cahier caractère',
    'Cahierembl?Me': 'cahier emblème',
    'Cà¿tés': 'côtés',
    'crÃ¿me': 'crème',
    '¿Notre': "Notre", 
    '¿Croquis': "croquis",
    'Caract¿ristique': "caractéristique", 
    '¿paisse': "épaisse",
    "â¿â¿by": "by",
    's¿y': "s'y", 
    'l¿échelle': "l'échelle",
    'c¿est': "c'est", 
    'd¿été': "d'été", 
    's¿est': "s'est", 
    'aujourd¿hui': "aujourd'hui",
    'Mat¿ri': "matéri",
    'op¿ration': "opération",
    'r¿fl¿chissant': "réfléchissant",
    
    'm¿tal': "métal",
    'cr¿maill¿re': "crémaillère",
    "r¿union": "réunion",
    'r¿tro': "rétro",
    'poly¿thyl¿ne': "polyéthylène",
    'jeuneou': "jeune ou",
    'langerL': "langer l",
    'rag¿narok': "ragnarok",
    'midg¿rd': "midgard",
    "¿ø": "diamètre",
    ' bã©bã©': "bébé",
     'doublã©e': "doublée",
     'rétro¿clair': "rétroéclair",
     'qualitã': 'qualité',
     're¿gulie': "régulier",
     'ãªtre': "être"
    
}



CLASSIC_PATTERNS_DICT = {
    '¿rieur': "érieur",
    'd¿co': "déco",
    'd¿ca': "déca",
    'lit¿': "lité",
    'min¿e': "minée",
    'iqu¿e': "iquée",
    '¿lectr': "électr",
    'p¿riph': "périph",
    'd¿tect': "détect",
    'yr¿ne': "yrene",
    'yl¿ne': "ylene",
    "¿last": "elast",
    "r¿frig": "refrig",
    "stom¿r": "stomer",
    "pr¿in": "préin",
     
    

}